### ISSUE TITLE
how to handle asyn commands?

### ISSUE THREAD

**Issue by rahpuser** [ArthurClemens/Javascript-Undo-Manager#17]
Hello, nice lib. I'm trying to add do/redo functionallity, the only issue I have is that some of my commands (do/redos) are async, so it turns into rare behavior when I click "ctrl+z" pretty fast, because the last undo call is not waiting for the firsts calls. Is there a way to handle this ?

thanks.

**Comment by xeii** [comment]
+1

**Comment by nonplus** [comment]
@xeii's approach will work if you're willing to ignore ctrl+z commands while an async undo is in progress (and you also need a similar guard on `isUndoing` when the user is performing a redo() operation). Also, you may need to add a check whether there is anything on the undo/redo stack, because the UndoManager does not call the callback if the undo/redo operation is a noop.

If you want to queue up undo/redo operations (i.e. the second ctrl+z is executed _after_ the first one is finished) you'll need to do something along this line:
```
var pending = [];

undoManager.setCallback(handleNext);

// Add undo/redo to queue of pending operations
function enqueueOperation(callback) {
   pending.push(callback);
   if (pending.length === 1) {
      handleNext();
   }
}

// Perform the next undo/redo operation
function handleNext() {
   if (pending.length) {
      pending.unshift()();
   }
}

function whenUndoIsCalled() {
   enqueueOperation(function() {
      if (undoManager.hasUndo()) {
         undoManager.undo();
      } else {
         handleNext();
      }
   );
}

function whenRedoIsCalled() {
   enqueueOperation(function() {
      if (undoManager.hasRedo()) {
         undoManager.redo();
      } else {
         handleNext();
      }
   );
}
```

**Comment by xeii** [comment]
Thank you for your reply. I got it working now.

**Comment by rwwagner90** [comment]
@nonplus is that example complete? It seems like `hasUndo` and `hasRedo` are not used? Did anyone figure out how to do async correctly?
